### ISSUE TITLE
libros_babel_fish.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ymohamed08** [StefanFabian/qml_ros_plugin#1]
**Describe the bug**

When i try and run any of the examples this error comes up

**To Reproduce**
1. git clone babel fish repo into catkin_ws/src 
2. catkin_make, then sudo make install from the build folder in catkin
3. git clone qml_ros_plugin into catkin_ws and sudo make install from the build folder in catkin 

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - ROS Melodic

**Additional info**
- the libros_babel_fish.so is in the catkin_ws/install_isolated/lib 
- while qml plugin is in /usr/lib/x86_64-linux-gnu/qt5/qml/Ros/libqml_ros_plugin.so

- if I try and make qml_plugin outside catkin_ws is show that catkin_pkg is not found install or check if its the PYTHONPATH

**Comment by StefanFabian** [comment]
I'm a bit unfamiliar with your setup.
Are you sourcing your ROS workspace?
Is there a reason you are using the deprecated `catkin_make` rather than `catkin_tools`, i.e. `catkin build`?

**Comment by ymohamed08** [comment]
Yes am sourcing my workspace.
Am not sure, about the difference myself. What would you recommend in this case?
Or what would be the usual way of installing babel fish, as it's not installed in a location that the qml plugin recognizes

Youssef Mohamed
________________________________

**Comment by StefanFabian** [comment]
Can you try the minimal setup outlined [here](https://github.com/tu-darmstadt-ros-pkg/hector_rviz_overlay/issues/2#issuecomment-1042088677)?
You don't need `hector_rviz_overlay` in this case but the rest is the same except the last step where you run the examples instead of rviz.

**Comment by ymohamed08** [comment]
When i do cmake .. This happens 
![image](https://user-images.githubusercontent.com/52243129/154476117-893a957f-c936-4fd9-8cd6-1109bf0c6f3e.png)

I can go to the build folder and sudo make install, but then the same problem of not finding the babel fish again 

![image](https://user-images.githubusercontent.com/52243129/154476472-8964328f-0f85-48ea-8457-4a4a6b679f10.png)

**Comment by StefanFabian** [comment]
Yeah running make install makes no sense if it didn't build properly which it can't if cmake failed.
There seems to be something broken with your ROS setup.
Did you install `python-catkin-tools`?
You can check that using `dpkg -l | grep catkin-tools`. If there is no output, install it using `sudo apt install python-catkin-tools`.

Edit: I just saw your python executable is in a bin folder in your home folder?
That's a weird setup. Do you maybe have some custom python installation or virtualenv?
That might explain why ROS can't find the python packages it needs since they are installed in the default system-wide paths.

**Comment by ymohamed08** [comment]
catkin-tools is installed, not sure how to fix the python problem, I have two versions of python installed, but not sure how to make cmake point to the right one. it just goes to the wrong version. even if catkin builds using the right python 
i have used `catkin build -DPYTHON_EXECUTABLE=/usr/bin/python` to build the workspace

**Comment by StefanFabian** [comment]
You can check you `$PATH` variable. If you remove your `/home/.../bin` folder from the path it shouldn't use that python executable.

**Comment by ymohamed08** [comment]
Thank you so much, this has been fixed by pointing cmake to the right python (as you have noticed) using `cmake -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python ..` after sourcing. 

Although after installation, when I run my project after importing `Ros 1.0` it cannot find `libros_babel_fish.so` as I have shown you in the screenshot above. Is there a way to make it point to where rosbabel is? or how to I source the catkin space before running my project for it to see it? 

Thank you again for your replies.

**Comment by StefanFabian** [comment]
As I wrote in the linked minimal setup, you source your workspace using `source {WS_ROOT}/devel/setup.bash`.
Inside that `devel` folder you should find a `lib` folder which should contain `libros_babel_fish.so`.
After sourcing your workspace, the `devel` folder should be listed in the `$CMAKE_PREFIX_PATH` environment variable and the `lib` folder should be listed in the `$LD_LIBRARY_PATH` environment variable.
