### ISSUE TITLE
ROS 2 Support

### ISSUE THREAD

**Issue by rosterloh** [StefanFabian/qml_ros_plugin#3]
This is a really excellent project. Thank you for your work. I'm currently using ROS 2 for my project and was wondering if you had any intention to have a ROS 2 version of this plugin?

**Comment by StefanFabian** [comment]
I have already finished a ROS 2 version with full support but it requires ros2/rosidl_typesupport#114 to be merged.
Until that happens I could only release a version that supports publishing and subscribing but no actions or services.

**Comment by rosterloh** [comment]
Amazing! I'd be happy to test just pub/sub if you'd like another set of eyes. Do you think this plugin could ever be run with a standalone application outside of a ROS workspace?

**Comment by StefanFabian** [comment]
Well as long as you bundle it with all required libraries, I don't see why not.

**Comment by StefanFabian** [comment]
Just a quick heads up that the ROS2 version is now released.
As mentioned actions and service clients still require the fix which is yet to be merged.
https://github.com/StefanFabian/qml_ros2_plugin
