### ISSUE TITLE
module "Ros" is not installed

### ISSUE THREAD

**Issue by ussefdesouky** [StefanFabian/qml_ros_plugin#4]
I have gone through these steps:
1- cloned the repo and entered the repo folder
2- mkdir build && cd build
3- cmake ..
4- sudo make install
and I went through the build process successfully.

Then I tried to run the examples using the command line "qmlscense subscriber.qml", but this was the error:
file:///home/desouky/qml_ros_plugin-master/examples/subscriber.qml:5 module "Ros" is not installed

This is the qt [window:](url)
![Screenshot from 2022-12-17 16-52-55](https://user-images.githubusercontent.com/38999100/208247817-e03f5446-eba0-40fd-892b-9886ac2d77f5.png)

I am using ubuntu 18.4, ROS Melodic & qt 5.12

**Comment by StefanFabian** [comment]
What's your output for the following commands?
```
qmake --version
```
and
```
qmake -qt5 -query QT_INSTALL_QML
```

**Comment by ussefdesouky** [comment]
![Screenshot from 2022-12-19 22-01-36](https://user-images.githubusercontent.com/38999100/208510146-565a5d03-abb3-4888-ba84-bc9512da6e48.png)

**Comment by StefanFabian** [comment]
Your issue is that your system is configured to use Qt 4 as default. 
You can either change the default to Qt5 or start qmlscene with `qmlscene -qt5 ...`

**Comment by ussefdesouky** [comment]
I have changed my default version to 
```
QMake version 3.1
Using Qt version 5.9.5 in /usr/lib/x86_64-linux-gnu
```
but still the same problem

**Comment by StefanFabian** [comment]
Can you check if there is a `Ros` folder in `/usr/lib/x86_64-linux-gnu/qt5/qml/` which should contain two files: `qmldir` and `libqml_ros_plugin.so`.
If those are there, this is an issue with your Qt setup.

**Comment by ussefdesouky** [comment]
Solved it thanks, it is qt installation problem.

**Comment by ussefdesouky** [comment]
Solved it thanks, it was qt installation problem.
