### ISSUE TITLE
cmake ..   command error

### ISSUE THREAD

**Issue by Gcient** [StefanFabian/qml_ros_plugin#5]
![image](https://github.com/StefanFabian/qml_ros_plugin/assets/49514385/4ccf0bb1-f492-4168-813f-0f1a7c03377f)

When I execute the 'cmake ..' command, such an error occurs. In which directory do I need to put the ros_babel_fish project to work?
Looking forward to your reply, thank you

**Comment by StefanFabian** [comment]
You need to either install `ros_babel_fish` e.g. on Ubuntu 20.04 using apt `ros-noetic-ros-babel-fish` or clone ros_babel_fish in your catkin workspace.
See [catkin tools Quickstart](https://catkin-tools.readthedocs.io/en/latest/quick_start.html).
Then build the workspace, source it (important to do everytime you've built a new package), and then you should be able to build the project.
In case you are missing other dependencies, you might also want to run `rosdep install -i qml_ros_plugin` (this will only work if you've built `qml_ros_plugin` once using catkin) alternatively from the src or the qml_ros_plugin root dir `rosdep install -i --from-paths .`.
