### ISSUE TITLE
package.xml missing dependencies

### ISSUE THREAD

**Issue by SyZbidi** [StefanFabian/qml_ros_plugin#7]
Hi,

I installed the package for the purpose of using it only with ROS following the description [here](https://github.com/StefanFabian/qml_ros_plugin?tab=readme-ov-file#installation) but got the following error
`qmlscene: could not find a Qt installation of ''`

Reason is some of the dependencies listed in the [examples README](https://github.com/StefanFabian/qml_ros_plugin/tree/master/examples#examples) are not included in  the `package.xml`, so by running
 `rosdep install --from-paths src --ignore-src -r -y` 
the only package installed was `qml-module-qtquick2`.

Is there a reason why the rest of the dependencies are not features in the `package.xml` file?

Thanks

**Comment by StefanFabian** [comment]
Sorry for the late reply! I have been very busy lately.
Yes, the other packags are technically not required for the plugin to work.
`qmlscene` is only needed for the examples not by the plugin itself and I try to keep dependencies minimal.
It could be explained better in the README though. Unfortunately, I don't know if I will have the time in the near future to rewrite it.
